#! /bin/sh

set -e
export PATH="/usr/sbin:$PATH"

SERVICE_NAME="${1:-org.webosbrew.hbchannel.service}"
RESCAN_NEEDED=0

# Executes a sed command in arg1 on a file, copies it over into the path in
# arg2 if changed.
safesed() {
    target=/tmp/_safesed.$$
    if [[ ! -f $2 ]]; then
        echo "[!] $2 does not exist..."
    else
        sed $1 $2 > $target
        if ! diff $2 $target ; then
            cp $target $2
            echo "[+] File changed"
            RESCAN_NEEDED=1
        fi
    fi
}

if [[ -f "/var/palm/ls2-dev/services/pub/$SERVICE_NAME.service" ]]; then
    echo "[~] Running on webOS <3"

    echo "[ ] Unjailing '$SERVICE_NAME'..."
    safesed 's;/usr/bin;/media/developer/apps/usr/palm/services/org.webosbrew.hbchannel.service;' /var/palm/ls2-dev/services/pub/$SERVICE_NAME.service
    safesed 's;/usr/bin;/media/developer/apps/usr/palm/services/org.webosbrew.hbchannel.service;' /var/palm/ls2-dev/services/prv/$SERVICE_NAME.service

    echo "[ ] Extending ls2 permissions for '$SERVICE_NAME'..."
    safesed 's;"outbound":\[\];"outbound":["*"];g' /var/palm/ls2-dev/roles/prv/$SERVICE_NAME.json
else
    echo "[ ] Unjailing '$SERVICE_NAME'..."
    safesed 's;/usr/bin;/media/developer/apps/usr/palm/services/org.webosbrew.hbchannel.service;' /var/luna-service2-dev/services.d/$SERVICE_NAME.service

    echo "[ ] Extending ls2 permissions for '$SERVICE_NAME'..."
    safesed 's;public;all;g' /var/luna-service2-dev/client-permissions.d/$SERVICE_NAME.service.json

    echo "[ ] Exposing public API for '$SERVICE_NAME'..."
    safesed "s;$SERVICE_NAME.group;public;g" /var/luna-service2-dev/api-permissions.d/$SERVICE_NAME.api.json
fi

if [ $RESCAN_NEEDED -eq 1 ]; then
    echo "[+] Refreshing services..."
    ls-control scan-volatile-dirs
else
    echo "[-] No changes, no rescan needed"
fi
